### ISSUE TITLE
Got ClassNotFoundException: org.apache.beam.samples.EventsByLocation while running the examples

### ISSUE THREAD

**Issue by simeonmalchev** [Talend/beam-samples#5]
Hi,

First to say, thanks for providing this project. I wonder whether you'll be able to assist me with running the examples. When I tried
```
mvn exec:java -Dexec.mainClass=org.apache.beam.samples.EventsByLocation -Pdirect-runner -Dexec.args="--runner=DirectRunner --input=/home/dataset/gdelt/2014-2016/201605*.zip --output=/tmp/gdelt/output/"
```
I got `java.lang.ClassNotFoundException: org.apache.beam.samples.EventsByLocation`. I have attached the full log from the above command with the `-X` option added to the `mvn` params.
[beam-example-error.txt](https://github.com/jbonofre/beam-samples/files/3319313/beam-example-error.txt)

I'm new to Beam; it might be just a simple configuration error in my environment that is causing this exception. If you can suggest what might be wrong that would be great.

Cheers,
Simeon

**Comment by iemejia** [comment]
Weird maybe it was in an incorrect path. Did this already work for you? The class path seems to be ok but in the EventsByLocation subproject.

https://github.com/jbonofre/beam-samples/blob/master/EventsByLocation/src/main/java/org/apache/beam/samples/EventsByLocation.java

**Comment by simeonmalchev** [comment]
Hi @iemejia,

I actually have the same problem with all runners. The first post above was while trying to run the examples with direct-runner, and here is the log when I try to run them with  flink-runner. 
[beam-examples-classpath.txt](https://github.com/jbonofre/beam-samples/files/3357798/beam-examples-classpath.txt)

This is my `mvn -version` output:
```
mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T04:33:14+10:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.2", arch: "x86_64", family: "mac"
```

Can you please include your `mvn -version` output? The problem might be due to some differences in mvn or java versions.

**Comment by jbonofre** [comment]
Let me try to reproduce, it worked before afair.

**Comment by simeonmalchev** [comment]
Hey @jbonofre, I'm not sure how did you go with this. I couldn't run these examples but I still learned what I needed to learn from the sources and this project was still quite helpful to me. So if you wish you can close this issue; or I can close it myself in a few days.

**Comment by simeonmalchev** [comment]
As I mentioned earlier, this is not longer a problem for me, I'm closing this issue.

**Comment by iemejia** [comment]
I just cross checked this issue and found another minor bug in the Options of that Pipeline, so please update to the latest master. In any case, it seems that you were executing the Pipeline without compiling it first, and it could not find the classes for that reason. If you do this it should work now.

`mvn compile exec:java -Dexec.mainClass=org.apache.beam.samples.EventsByLocation -Pdirect-runner -Dexec.args="--runner=DirectRunner --input=/home/dataset/gdelt/2014-2016/201605*.zip --output=/tmp/gdelt/output/"`

**Comment by simeonmalchev** [comment]
Hi @iemejia, I just tried and this time everything worked fine. I'm not sure what I did wrong before but now things look good.
Thanks again.
